# Generated by Django 3.0.4 on 2020-03-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='weather_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
